#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/hunter" ] && [ ! -L "/etc/init.d/hunter" ]; then
		if [ "`md5sum \"/etc/init.d/hunter\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' hunter | sed -n -e \"\\\\' /etc/init.d/hunter '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/hunter has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/hunter" "/etc/init.d/hunter.dpkg-bak"
		else
			rm -f "/etc/init.d/hunter"
		fi
	fi
fi
# End automatically added section
